name: Run my python
on:
  push: #do this push
jobs:
  build:
    name: Set up penvironment 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
    - name: Run my python
      run: |
         python3 test.py 