name: Run Python Test
on:
  push:
jobs:
  build:
    name: run python
    runs-on: ububtu-lastest
    steps:
    - uses: actions/checkout@v2
    - name: Run python
      run: |
         python3 test.py 